### ISSUE TITLE
link/device name must be < 16 characters

### ISSUE THREAD

**Issue by onelesd** [InstantChannel/netns#1]
Using the current naming convention for link/device names, it is possible the name exceeds 15 characters, leading to creation failures:

```
argument "d107-152-208-128" is wrong: "name" too long
```

See: http://stackoverflow.com/questions/24932172/what-length-can-a-network-interface-name-have

**Comment by jamesloosli** [comment]
https://github.com/InstantChannel/netns/commit/6f6e946c08a3cc1d17a497484ca845c6987db85a

Test pls.
